import { lazy } from 'react'
import { DASHBOARDS_PREFIX_PATH } from '@/constants/route.constant'
import { Role, Permission } from '@/utils/rbac/types'
import type { Routes } from '@/@types/routes'

const dashboardsRoute: Routes = [
    {
        key: 'dashboard.dashboard',
        path: `${DASHBOARDS_PREFIX_PATH}`,
        component: lazy(() => import('@/views/dashboard/Dashboard')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.OPERATOR, Role.CLIENT],
        permissions: [Permission.VIEW_DASHBOARD],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'companies.list',
        path: '/companies',
        component: lazy(() => import('@/views/companies/CompaniesList')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.VIEW_COMPANIES],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'companies.create',
        path: '/companies/create',
        component: lazy(() => import('@/views/companies/CompanyCreate')),
        roles: [Role.SUPERADMIN],
        permissions: [Permission.CREATE_COMPANY],
        meta: {
            header: {
                title: 'Crear empresa',
                description: 'Registra una nueva empresa en Locentr.',
                contained: true,
            },
            footer: false,
        },
    },
    {
        key: 'companies.subcompanyCreate',
        path: '/companies/subcompany/create',
        component: lazy(() => import('@/views/companies/CompanySubCreate')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.CREATE_COMPANY],
        meta: {
            header: {
                title: 'Crear subempresa',
                description: 'Registra una subempresa vinculada a una empresa de Locentr.',
                contained: true,
            },
            footer: false,
        },
    },
    {
        key: 'companies.edit',
        path: '/companies/:id/edit',
        component: lazy(() => import('@/views/companies/CompanyEdit')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.EDIT_COMPANY],
        meta: {
            header: {
                title: 'Editar empresa',
                description: 'Actualiza la información administrativa de la empresa.',
                contained: true,
            },
            footer: false,
        },
    },
    {
        key: 'companies.details',
        path: '/companies/:id',
        component: lazy(() => import('@/views/companies/CompanyDetails')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.VIEW_COMPANIES],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'accessManagement.list',
        path: '/access',
        component: lazy(() => import('@/views/accessManagement/AccessManagement')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.OPERATOR, Role.CLIENT],
        permissions: [Permission.VIEW_ACCESS_MANAGEMENT],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'documents.list',
        path: '/documents',
        component: lazy(() => import('@/views/documents')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.OPERATOR, Role.CLIENT],
        permissions: [Permission.VIEW_DOCUMENTS],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'auditLog.list',
        path: '/audit',
        component: lazy(() => import('@/views/auditLog')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.VIEW_AUDIT_LOG],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'users.list',
        path: '/users',
        component: lazy(() => import('@/views/users/UsersList/UsersList')),
        roles: [Role.SUPERADMIN],
        permissions: [Permission.VIEW_USERS],
    },
    {
        key: 'users.create',
        path: '/users/create',
        component: lazy(() => import('@/views/users/UsersCreate/UsersCreate')),
        roles: [Role.SUPERADMIN],
        permissions: [Permission.CREATE_USER],
        meta: {
            header: {
                title: 'Crear usuario',
                description: 'Registra usuarios y asigna sus roles dentro de Locentr.',
                contained: true,
            },
            footer: false,
        },
    },
    {
        key: 'users.edit',
        path: '/users/:id/edit',
        component: lazy(() => import('@/views/users/UserEditView')),
        roles: [Role.SUPERADMIN],
        permissions: [Permission.EDIT_USER],
        meta: {
            header: {
                title: 'Editar usuario',
                description: 'Actualiza la información y el rol del usuario.',
                contained: true,
            },
            footer: false,
        },
    },
    {
        key: 'users.details',
        path: '/users/:id',
        component: lazy(() => import('@/views/users/UserDetailsView')),
        roles: [Role.SUPERADMIN],
        permissions: [Permission.VIEW_USERS],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'supportTickets.list',
        path: '/tickets',
        component: lazy(() => import('@/views/supportTickets/SupportTicketsList')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.CLIENT],
        permissions: [Permission.VIEW_SUPPORT_TICKETS],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'supportTickets.details',
        path: '/tickets/:ticketId',
        component: lazy(() => import('@/views/supportTickets/SupportTicketDetails')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.CLIENT],
        permissions: [Permission.VIEW_SUPPORT_TICKETS],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'dashboard.legacy',
        path: '/dashboards',
        component: lazy(() => import('@/views/dashboard/Dashboard')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.OPERATOR, Role.CLIENT],
        permissions: [Permission.VIEW_DASHBOARD],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'accessManagement.legacy',
        path: '/access-management',
        component: lazy(() => import('@/views/accessManagement/AccessManagement')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.OPERATOR, Role.CLIENT],
        permissions: [Permission.VIEW_ACCESS_MANAGEMENT],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'auditLog.legacy',
        path: '/audit-log',
        component: lazy(() => import('@/views/auditLog')),
        roles: [Role.SUPERADMIN, Role.ADMIN],
        permissions: [Permission.VIEW_AUDIT_LOG],
        meta: { pageContainerType: 'contained' },
    },
    {
        key: 'supportTickets.legacy',
        path: '/support-tickets',
        component: lazy(() => import('@/views/supportTickets/SupportTicketsList')),
        roles: [Role.SUPERADMIN, Role.ADMIN, Role.CLIENT],
        permissions: [Permission.VIEW_SUPPORT_TICKETS],
        meta: { pageContainerType: 'contained' },
    },
]

export default dashboardsRoute
